### ISSUE TITLE
Upgrade to Mocha@10

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/bedrock-test#23]
Falling behind on 'mocha' dep here.

Even with `mocha@10` there is one related security vulnerability that should be addressed via this issue: https://github.com/mochajs/mocha/issues/4903

**Comment by aljones15** [comment]
This upgrades takes this library from `9` to `10`

Here is the relevant changelog: https://github.com/mochajs/mocha/blob/master/CHANGELOG.md

Here are the breaking changes:

- [ ] https://github.com/mochajs/mocha/issues/4845: Drop Node.js v12.x support ([@juergba](https://github.com/juergba))
    - [ ] not much of an issue, but do need to ensure `engines > 12` in `package.json` if not already set 
    - [ ] **NOTE: engines is not currently set in the package.json**
    - [ ] Adding the engines section is a breaking change.
- [ ] https://github.com/mochajs/mocha/issues/4848: Drop Internet-Explorer-11 support ([@juergba](https://github.com/juergba))
    - [ ] this could require changes in `bedrock-karma`, but is unlikely to cause any issues 
- [ ] https://github.com/mochajs/mocha/issues/4857: Drop AMD/RequireJS support ([@juergba](https://github.com/juergba))
    - [ ] We're not using `requireJs`, but this seems like a good reminder to ensure this library uses es6 exports.
    - [ ] EDIT: library is already es6, but we should include the deprecation in changelog
- [ ] https://github.com/mochajs/mocha/issues/4866: Drop Growl notification support ([@juergba](https://github.com/juergba))
    - [ ] This does not effect any bedrock project, but should be noted in changelog
- [ ] https://github.com/mochajs/mocha/issues/4863: Rename executable bin/mocha to bin/mocha.js ([@juergba](https://github.com/juergba))
    - [ ]  This has little effect on this library
- [ ] https://github.com/mochajs/mocha/issues/4865: --ignore option in Windows: upgrade Minimatch ([@juergba](https://github.com/juergba))
    - [ ] no major effect, but changelong for this upgrade will need to note this and all other breaking changes 
- [ ] https://github.com/mochajs/mocha/issues/4861: Remove deprecated Runner signature ([@juergba](https://github.com/juergba))
    - [ ] this only effects passing `delay` to a test Runner, but as this library does use the `Runner` class progammatically a change will need to be made to ensure delay is passed correctly to Runner.

**Comment by mattcollier** [comment]
Landed in https://github.com/digitalbazaar/bedrock-test/blob/main/CHANGELOG.md#810---2023-04-18
